adding a 2021 and 2022 version of the 4868 tax form
sensible-hq/sensible-configuration-library pull request #64
Opened 2023-03-13 17:58 UTC by aNorthSense

(adding readme updates in last PR)

2023-03-16 20:01 UTC, aNorthSense commented
https://app.sensible.so/editor/?d=4868&c=2021&g=4868_2021_sample
https://app.sensible.so/editor/?d=4868&c=2022&g=4868_2022_sample

2023-03-16 23:29 UTC, angbonilla requested changes
Shared comments over slack

2023-03-17 17:06 UTC, angbonilla approved these changes

2023-03-17 17:07 UTC, angbonilla commented
🚢

2023-03-17 18:54 UTC, merged